package com.br.yat.gerenciador.model.enums;

import com.br.yat.gerenciador.util.MenuRegistry;
import com.br.yat.gerenciador.util.PermissionMenuMapper;

/**
 * Enumeração que representa as chaves de menus da aplicação.
 * <p>
 * Cada constante corresponde a uma funcionalidade específica organizada por módulos:
 * <ul>
 * <li>Dashboard</li>
 * <li>Cadastros</li>
 * <li>Consultas</li>
 * <li>Licenças</li>
 * <li>Financeiro</li>
 * <li>Relatórios</li>
 * <li>Auditoria</li>
 * <li>Configuração</li>
 * <li>Ajuda</li>
 * </ul>
 * </p>
 * 
 * <p>Utilizada para registro e controle de menus em {@link MenuRegistry}
 * e mapeamento de permissões em {@link PermissionMenuMapper}.</p>
 */
public enum MenuChave {
	
	DASHBOARD_GERAL,
	DASHBOARD_ALERTAS,
	DASHBOARD_LICENCAS_A_VENCER,
	DASHBOARD_LICENCAS_BLOQUEADAS,
	DASHBOARD_PAGAMENTOS_PENDENTES,
	
	CADASTROS_EMPRESA_CLIENTE,
	CADASTROS_USUARIO,
	CADASTROS_PLANO_DE_LICENCA,
	
	CONSULTAS_EMPRESAS_CLIENTES,
	CONSULTAS_USUARIOS,
	CONSULTAS_PLANO_DE_LICENCA,
	CONSULTAS_LICENCAS,
	CONSULTAS_DISPOSITIVOS,
	CONSULTAS_PAGAMENTOS,
	
	LICENCAS_GERAR_LICENCA,
	LICENCAS_RENOVAR_LICENCA,
	LICENCAS_ATIVAR_BLOQUEAR_LICENCA,
	LICENCAS_DISPOSITIVOS_VINCULADOS,
	LICENCAS_HISTORICO_DA_LICENCA,
	
	FINANCEIRO_REGISTRAR_PAGAMENTO,
	FINANCEIRO_CONSULTAR_PAGAMENTOS,
	FINANCEIRO_FATURAMENTO_RECEITA,
	FINANCEIRO_RELATORIOS,
	
	RELATORIOS_GERENCIAIS_LICENCAS_ATIVAS_EXPERIDAS,
	RELATORIOS_GERENCIAIS_LICENCAS_A_VENCER,
	RELATORIOS_GERENCIAIS_RECEITA_POR_PERIODO,
	RELATORIOS_GERENCIAIS_RECEITA_POR_PLANO,
	RELATORIOS_GERENCIAIS_EMPRESAS_POR_PLANO,
	RELATORIOS_GERENCIAIS_DISPOSITIVOS_POR_LICENCA,
	RELATORIOS_GERENCIAIS_USUARIOS_POR_EMPRESA,
	
	AUDITORIA_LOG_DO_SISTEMA,
	AUDITORIA_HISTORICO_DE_LICENCAS,
	
	CONFIGURACAO_EMPRESA_FORNECEDORA,
	CONFIGURACAO_PARAMETRO_SISTEMA,
	CONFIGURACAO_PARAMETRO_LICENCA,	
	CONFIGURACAO_SEGURANCA,
	CONFIGURACAO_PERMISSAO,
	CONFIGURACAO_USUARIOS_PERMISSOES,
	CONFIGURACAO_MANUTENCAO,
	CONFIGURACAO_BACKUP_DE_DADOS,
	CONFIGURACAO_RESTAURAR_BACKUP,
	CONFIGURACAO_LIMPEZA_DE_LOGS,
	CONFIGURACAO_VERSAO_DO_SISTEMA,

	AJUDA_MANUAL_DO_SISTEMA,
	AJUDA_SUPORTE_TECNICO,
	AJUDA_SOBRE_O_SISTEMA,
	AJUDA_VERIFICAR_ATUALIZACOES

}
