package com.br.yat.gerenciador.model.enums;

public enum ParametroChave {

	LOGIN_MAX_TENTATIVAS("LOGIN_MAX_TENTATIVAS"), 
	LOGIN_TEMPO_BLOQUEIO_MIN("LOGIN_TEMPO_BLOQUEIO_MIN"),
	FORCAR_TROCA_SENHA_DIAS("FORCAR_TROCA_SENHA_DIAS"),
	TEMPO_SESSAO_MIN("TEMPO_SESSAO_MIN"),
	LICENCA_ALERTA_EXPIRACAO_DIAS("LICENCA_ALERTA_EXPIRACAO_DIAS"),
	LICENCA_MAX_DISPOSITIVOS("LICENCA_MAX_DISPOSITIVOS"),
	LICENCA_ATIVA_PADRAO("LICENCA_ATIVA_PADRAO"),
	LOG_SISTEMA_ATIVO("LOG_SISTEMA_ATIVO"),
	LOG_NIVEL_PADRAO("LOG_NIVEL_PADRAO"),
	TEMPO_REFRESH_DASHBOARD("TEMPO_REFRESH_DASHBOARD"),
	EMAIL_NOTIFICACAO_ATIVO("EMAIL_NOTIFICACAO_ATIVO"),
	EMAIL_ALERTA_LICENCA("EMAIL_ALERTA_LICENCA"),
	SENHA_MIN_TAMANHO("SENHA_MIN_TAMANHO"),

	SENHA_EXPIRA_DIAS("SENHA_EXPIRA_DIAS");

	private final String chaveBanco;

	ParametroChave(String chaveBanco) {
		this.chaveBanco = chaveBanco;
	}

	public String getChaveBanco() {
		return chaveBanco;
	}
}
