-- MySQL Script generated by MySQL Workbench
-- Tue Feb  3 07:22:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_gerenciador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_gerenciador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gerenciador` DEFAULT CHARACTER SET utf8 ;
USE `db_gerenciador` ;

-- -----------------------------------------------------
-- Table `db_gerenciador`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(50) NOT NULL,
  `logradouro` VARCHAR(150) NOT NULL,
  `complemento` VARCHAR(150) NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  `nome_fantasia` VARCHAR(200) NOT NULL,
  `razao_social` VARCHAR(200) NULL,
  `tipo_documento` VARCHAR(10) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `insc_estadual` VARCHAR(30) NULL,
  `contribuinte_icms` VARCHAR(50) NULL,
  `insc_municipal` VARCHAR(30) NULL,
  `data_fundacao` DATE NULL,
  `cnae` VARCHAR(100) NULL,
  `porte_empresa` VARCHAR(50) NULL,
  `natureza_juridica` VARCHAR(50) NULL,
  `crt` INT NULL,
  `regime_tributario` VARCHAR(50) NULL,
  `capital_social` DECIMAL(15,2) NULL,
  `situacao_cadastral` VARCHAR(20) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `documento_UNIQUE` (`tipo_documento` ASC, `documento` ASC) INVISIBLE,
  INDEX `fk_empresa_fornecedora_endereco_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_gerenciador`.`endereco` (`id_endereco`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`plano_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`plano_licenca` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `quantidade_maxima` INT NOT NULL,
  `duracao_mes` INT NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`licenca_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`licenca_software` (
  `id_licenca` INT NOT NULL AUTO_INCREMENT,
  `chave` VARCHAR(512) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `versao` VARCHAR(30) NOT NULL,
  `assinatura` VARCHAR(512) NOT NULL,
  `ativa` TINYINT(1) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_plano` INT NOT NULL,
  `id_fornecedora` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_licenca`),
  UNIQUE INDEX `assinatura_UNIQUE` (`assinatura` ASC) VISIBLE,
  INDEX `licenca_fornecedora_idx` (`id_fornecedora` ASC) VISIBLE,
  INDEX `fk_licenca_plano_licenca_idx` (`id_plano` ASC) VISIBLE,
  INDEX `fk_licenca_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_licenca_empresa`
    FOREIGN KEY (`id_fornecedora`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_licenca_plano_licenca`
    FOREIGN KEY (`id_plano`)
    REFERENCES `db_gerenciador`.`plano_licenca` (`id_plano`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_licenca_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `status` CHAR(10) NOT NULL,
  `tentativas_falhas` INT NULL,
  `ultimo_login` DATETIME NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  `is_master` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_empresa_idx` (`id_empresa` ASC) INVISIBLE,
  UNIQUE INDEX `is_master_UNIQUE` (`is_master` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`historico_licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`historico_licenca` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `acao` VARCHAR(100) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `dados_anteriores` JSON NULL,
  `dados_novos` JSON NULL,
  `id_usuario` INT NOT NULL,
  `id_licenca` INT NOT NULL,
  PRIMARY KEY (`id_historico`),
  INDEX `historico_licenca_idx` (`id_licenca` ASC) VISIBLE,
  INDEX `fk_historico_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_historico_licenca`
    FOREIGN KEY (`id_licenca`)
    REFERENCES `db_gerenciador`.`licenca_software` (`id_licenca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_historico_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gerenciador`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`permissoes` (
  `id_permissoes` INT NOT NULL AUTO_INCREMENT,
  `chave` VARCHAR(100) NOT NULL,
  `tipo` CHAR(6) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_permissoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`usuario_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`usuario_permissoes` (
  `id_usuario` INT NOT NULL,
  `id_permissoes` INT NOT NULL,
  `ativa` TINYINT(1) NOT NULL,
  `expira_em` DATETIME NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_usuario_concedeu` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_permissoes`),
  INDEX `fk_permissoes_usuario_idx` (`id_permissoes` ASC) VISIBLE,
  INDEX `fk_permissoes_usuario_idx1` (`id_usuario_concedeu` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_permissoes`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gerenciador`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permissoes_usuario`
    FOREIGN KEY (`id_permissoes`)
    REFERENCES `db_gerenciador`.`permissoes` (`id_permissoes`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permissoes_usuario_permissoes`
    FOREIGN KEY (`id_usuario_concedeu`)
    REFERENCES `db_gerenciador`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`dispositivo` (
  `id_dispositivo` INT NOT NULL AUTO_INCREMENT,
  `mac` CHAR(17) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_licenca` INT NOT NULL,
  PRIMARY KEY (`id_dispositivo`),
  INDEX `fk_dispositivo_licenca_idx` (`id_licenca` ASC) VISIBLE,
  UNIQUE INDEX `mac_UNIQUE` (`mac` ASC) VISIBLE,
  CONSTRAINT `fk_dispositivo_licenca`
    FOREIGN KEY (`id_licenca`)
    REFERENCES `db_gerenciador`.`licenca_software` (`id_licenca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `metodo` VARCHAR(60) NOT NULL,
  `status` VARCHAR(60) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_licenca` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_pagamento_licenca_idx` (`id_licenca` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_licenca`
    FOREIGN KEY (`id_licenca`)
    REFERENCES `db_gerenciador`.`licenca_software` (`id_licenca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`log_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`log_sistema` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `acao` VARCHAR(255) NOT NULL,
  `entidade` VARCHAR(50) NULL,
  `id_entidade` INT NULL,
  `dados_anteriores` JSON NULL,
  `dados_novos` JSON NULL,
  `sucesso` TINYINT(1) NOT NULL,
  `mensagem_erro` VARCHAR(255) NULL,
  `ip_origem` VARCHAR(45) NULL,
  `data_hora` DATETIME NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `fk_log_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_log_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gerenciador`.`usuario` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`contato_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`contato_empresa` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `tipo_contato` VARCHAR(30) NULL,
  `valor` VARCHAR(200) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_contato`),
  INDEX `fk_empresa_contato_empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_contato_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`representante_legal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`representante_legal` (
  `id_representante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `rg` VARCHAR(20) NULL,
  `cargo` VARCHAR(100) NULL,
  `nacionalidade` VARCHAR(50) NULL,
  `estado_civil` VARCHAR(50) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_representante`),
  INDEX `fk_empresa_representante_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_representante_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`informacoes_complementares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`informacoes_complementares` (
  `id_info` INT NOT NULL AUTO_INCREMENT,
  `logotipo` VARCHAR(50) NULL,
  `numero_funcionarios` INT NULL,
  `ramo_atividade` VARCHAR(200) NULL,
  `observacoes` TEXT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_info`),
  INDEX `fk_empresa_informacoes_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_informacoes_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`dados_bancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`dados_bancarios` (
  `id_banco` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(100) NOT NULL,
  `codigo_banco` INT NOT NULL,
  `agencia` VARCHAR(20) NOT NULL,
  `conta` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(60) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_banco`),
  INDEX `fk_banco_empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_banco_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`documento_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`documento_empresa` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_empresa_documento_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_documento_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_gerenciador`.`empresa` (`id_empresa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`parametro_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`parametro_sistema` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT,
  `chave` VARCHAR(100) NOT NULL,
  `valor` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_parametro`),
  UNIQUE INDEX `chave_UNIQUE` (`chave` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`menu_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`menu_sistema` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `chave` VARCHAR(100) NOT NULL,
  `modulo` VARCHAR(50) NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_menu`),
  UNIQUE INDEX `chave_UNIQUE` (`chave` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gerenciador`.`permissao_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gerenciador`.`permissao_menu` (
  `id_permissao` INT NOT NULL,
  `id_menu` INT NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `atualizado_em` DATETIME NOT NULL,
  `deletado_em` DATETIME NULL,
  PRIMARY KEY (`id_permissao`, `id_menu`),
  INDEX `fk_permissao_menu_idx` (`id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_menu_permissoes`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `db_gerenciador`.`permissoes` (`id_permissoes`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permissao_menu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `db_gerenciador`.`menu_sistema` (`id_menu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
